# NOTE: This file is regenerated by .github/workflows/release.yml (update-formula
# job) on every tagged release from Formula/conload.rb.template. The sha256
# values below are placeholders until the first v1.0.1 CI run replaces them
# with the real hashes of the published conload-mac.jar / conload-linux.jar.
class Conload < Formula
  desc "Context layer for CLI coding agents — Confluence/Jira/GitHub as Markdown"
  homepage "https://github.com/soft-am/conload"
  version "1.0.1"
  license "Apache-2.0"
  depends_on "openjdk@21"

  on_macos do
    url "https://github.com/soft-am/conload/releases/download/v1.0.1/conload-mac.jar"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  on_linux do
    url "https://github.com/soft-am/conload/releases/download/v1.0.1/conload-linux.jar"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  def install
    jar_name = Dir["conload-*.jar"].first
    libexec.install jar_name
    (bin/"conload").write <<~SH
      #!/bin/bash
      exec "#{Formula["openjdk@21"].opt_bin}/java" -jar "#{libexec}/#{jar_name}" "$@"
    SH
  end

  test do
    assert_predicate (bin/"conload"), :executable?
  end
end
